### ISSUE TITLE
App no longer appears to be switching.

### ISSUE THREAD

**Issue by ThePastorJ** [adirh3/Sonar.AutoSwitch#19]
I haven't changed anything apart from updating steelseries gg. I'm on the latest version, 52.0.0. Maybe something's changed there, mind taking a look when you get time?

**Comment by adirh3** [comment]
@ThePastorJ Thanks for letting me know, they changed something in 52.0.0.
Just pushed a release with a fix, feel free to reopen if it still doesn't work for you.
