### ISSUE TITLE
Database location has changed

### ISSUE THREAD

**Issue by JohnnyDeeee** [adirh3/Sonar.AutoSwitch#3]
The Sonar database location is `C:\ProgramData\SteelSeries\GG\apps\sonar\db\database.db` instead of https://github.com/adirh3/Sonar.AutoSwitch/blob/master/Sonar.AutoSwitch/Services/SteelSeriesSonarService.cs#L21
(GG Version: 28.1.0)

**Comment by adirh3** [comment]
Thanks! Seems like 28.1 had multiple breaking changes.
I will try to push a fix later today.

**Comment by adirh3** [comment]
@JohnnyDeeee I fixed all 28.1.0 issues I could find in the latest release, let me know if it works for you.

**Comment by JohnnyDeeee** [comment]
This works in 28.1.0!
